name: live_streaming_flutter_app
description: A new Flutter project.

publish_to: 'none' # Remove this line if you wish to publish to pub.dev

version: 1.0.0+1

environment:
  sdk: ">=2.15.1 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.2
  agora_rtc_engine: ^3.3.2
  animated_text_kit: ^4.1.1
  cloud_firestore: ^1.0.3
  firebase_auth: ^1.0.1
  firebase_core: ^1.0.4
  firebase_storage: ^8.0.4
  flutter_spinkit: ^5.0.0
  flutter_svg: ^0.22.0
  font_awesome_flutter: ^9.0.0
  google_sign_in: ^5.0.1
  image_picker: ^0.7.4
  intl: ^0.17.0
  page_transition: ^1.1.7+6
  permission_handler: ^6.1.1
  provider: ^5.0.0
  random_string: ^2.1.0
  top_snackbar_flutter: ^1.0.0
  transparent_image: ^2.0.0
  persistent_bottom_nav_bar: ^4.0.2
  shared_preferences: ^2.0.5
  cached_network_image: ^3.0.0
  hexcolor: ^2.0.3
  wakelock: ^0.5.0+2
  agora_rtm: ^0.9.14
  random_color: ^1.0.5
  data_connection_checker: ^0.3.4


dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^1.0.0

flutter:

  uses-material-design: true

  assets:
    - assets/

  fonts:
    - family: PopR
      fonts:
        - asset: fonts/Poppins-Regular.ttf
    - family: PopM
      fonts:
        - asset: fonts/Poppins-Medium.ttf
    - family: PopS
      fonts:
        - asset: fonts/Poppins-SemiBold.ttf
    - family: PopB
      fonts:
        - asset: fonts/Poppins-Bold.ttf


